[workspace]
resolver = "2"
members = [
    "crates/rusty_time-core",
    "crates/rusty_time-nts",
    "crates/rusty_time-clock",
    "crates/rusty_time-api",
    "crates/rusty_time-daemon",
    "crates/rusty_time-ctl",
    "crates/rusty_time-wasm",
    "crates/rusty_time-alloc",
    "crates/rusty_time-sim",
]

[workspace.package]
version = "0.1.10"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/remade-with-rust/rusty_time"
homepage = "https://www.mata.network/"
rust-version = "1.95"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
rusty_time-core = { path = "crates/rusty_time-core", version = "0.1.10" }
rusty_time-nts = { path = "crates/rusty_time-nts", version = "0.1.10" }
rusty_time-clock = { path = "crates/rusty_time-clock", version = "0.1.10" }
rusty_time-api = { path = "crates/rusty_time-api", version = "0.1.10" }
rusty_time-alloc = { path = "crates/rusty_time-alloc", version = "0.1.10" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "thin"
codegen-units = 1
